/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ShopeeReviewRouteImport } from './routes/shopee-review'
import { Route as ApiShopeeReviewCookieTestRouteImport } from './routes/api/shopee-review/cookie-test'
import { Route as ApiShopeeReviewHealthRouteImport } from './routes/api/shopee-review/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopeeReviewRoute = ShopeeReviewRouteImport.update({
  id: '/shopee-review',
  path: '/shopee-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeReviewCookieTestRoute =
  ApiShopeeReviewCookieTestRouteImport.update({
    id: '/api/shopee-review/cookie-test',
    path: '/api/shopee-review/cookie-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopeeReviewHealthRoute = ApiShopeeReviewHealthRouteImport.update({
  id: '/api/shopee-review/health',
  path: '/api/shopee-review/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/shopee-review': typeof ShopeeReviewRoute
  '/api/shopee-review/cookie-test': typeof ApiShopeeReviewCookieTestRoute
  '/api/shopee-review/health': typeof ApiShopeeReviewHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/shopee-review': typeof ShopeeReviewRoute
  '/api/shopee-review/cookie-test': typeof ApiShopeeReviewCookieTestRoute
  '/api/shopee-review/health': typeof ApiShopeeReviewHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/shopee-review': typeof ShopeeReviewRoute
  '/api/shopee-review/cookie-test': typeof ApiShopeeReviewCookieTestRoute
  '/api/shopee-review/health': typeof ApiShopeeReviewHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/shopee-review'
    | '/api/shopee-review/cookie-test'
    | '/api/shopee-review/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/shopee-review'
    | '/api/shopee-review/cookie-test'
    | '/api/shopee-review/health'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/shopee-review'
    | '/api/shopee-review/cookie-test'
    | '/api/shopee-review/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ShopeeReviewRoute: typeof ShopeeReviewRoute
  ApiShopeeReviewCookieTestRoute: typeof ApiShopeeReviewCookieTestRoute
  ApiShopeeReviewHealthRoute: typeof ApiShopeeReviewHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopee-review': {
      id: '/shopee-review'
      path: '/shopee-review'
      fullPath: '/shopee-review'
      preLoaderRoute: typeof ShopeeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/cookie-test': {
      id: '/api/shopee-review/cookie-test'
      path: '/api/shopee-review/cookie-test'
      fullPath: '/api/shopee-review/cookie-test'
      preLoaderRoute: typeof ApiShopeeReviewCookieTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/health': {
      id: '/api/shopee-review/health'
      path: '/api/shopee-review/health'
      fullPath: '/api/shopee-review/health'
      preLoaderRoute: typeof ApiShopeeReviewHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ShopeeReviewRoute: ShopeeReviewRoute,
  ApiShopeeReviewCookieTestRoute: ApiShopeeReviewCookieTestRoute,
  ApiShopeeReviewHealthRoute: ApiShopeeReviewHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
