/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ShopeeReviewRouteImport } from './routes/shopee-review'
import { Route as ApiShopeeReviewDataRouteImport } from './routes/api/shopee-review/data'
import { Route as ApiShopeeReviewHealthRouteImport } from './routes/api/shopee-review/health'
import { Route as ApiShopeeReviewLoginRouteImport } from './routes/api/shopee-review/login'
import { Route as ApiShopeeReviewLogoutRouteImport } from './routes/api/shopee-review/logout'
import { Route as ApiShopeeReviewSessionRouteImport } from './routes/api/shopee-review/session'
import { Route as ApiShopeeOauthCallbackRouteImport } from './routes/api/shopee/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopeeReviewRoute = ShopeeReviewRouteImport.update({
  id: '/shopee-review',
  path: '/shopee-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeReviewDataRoute = ApiShopeeReviewDataRouteImport.update({
  id: '/api/shopee-review/data',
  path: '/api/shopee-review/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeReviewHealthRoute = ApiShopeeReviewHealthRouteImport.update({
  id: '/api/shopee-review/health',
  path: '/api/shopee-review/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeReviewLoginRoute = ApiShopeeReviewLoginRouteImport.update({
  id: '/api/shopee-review/login',
  path: '/api/shopee-review/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeReviewLogoutRoute = ApiShopeeReviewLogoutRouteImport.update({
  id: '/api/shopee-review/logout',
  path: '/api/shopee-review/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeReviewSessionRoute = ApiShopeeReviewSessionRouteImport.update({
  id: '/api/shopee-review/session',
  path: '/api/shopee-review/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopeeOauthCallbackRoute = ApiShopeeOauthCallbackRouteImport.update({
  id: '/api/shopee/oauth/callback',
  path: '/api/shopee/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/shopee-review': typeof ShopeeReviewRoute
  '/api/shopee-review/data': typeof ApiShopeeReviewDataRoute
  '/api/shopee-review/health': typeof ApiShopeeReviewHealthRoute
  '/api/shopee-review/login': typeof ApiShopeeReviewLoginRoute
  '/api/shopee-review/logout': typeof ApiShopeeReviewLogoutRoute
  '/api/shopee-review/session': typeof ApiShopeeReviewSessionRoute
  '/api/shopee/oauth/callback': typeof ApiShopeeOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/shopee-review': typeof ShopeeReviewRoute
  '/api/shopee-review/data': typeof ApiShopeeReviewDataRoute
  '/api/shopee-review/health': typeof ApiShopeeReviewHealthRoute
  '/api/shopee-review/login': typeof ApiShopeeReviewLoginRoute
  '/api/shopee-review/logout': typeof ApiShopeeReviewLogoutRoute
  '/api/shopee-review/session': typeof ApiShopeeReviewSessionRoute
  '/api/shopee/oauth/callback': typeof ApiShopeeOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/shopee-review': typeof ShopeeReviewRoute
  '/api/shopee-review/data': typeof ApiShopeeReviewDataRoute
  '/api/shopee-review/health': typeof ApiShopeeReviewHealthRoute
  '/api/shopee-review/login': typeof ApiShopeeReviewLoginRoute
  '/api/shopee-review/logout': typeof ApiShopeeReviewLogoutRoute
  '/api/shopee-review/session': typeof ApiShopeeReviewSessionRoute
  '/api/shopee/oauth/callback': typeof ApiShopeeOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/shopee-review'
    | '/api/shopee-review/data'
    | '/api/shopee-review/health'
    | '/api/shopee-review/login'
    | '/api/shopee-review/logout'
    | '/api/shopee-review/session'
    | '/api/shopee/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/shopee-review'
    | '/api/shopee-review/data'
    | '/api/shopee-review/health'
    | '/api/shopee-review/login'
    | '/api/shopee-review/logout'
    | '/api/shopee-review/session'
    | '/api/shopee/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/shopee-review'
    | '/api/shopee-review/data'
    | '/api/shopee-review/health'
    | '/api/shopee-review/login'
    | '/api/shopee-review/logout'
    | '/api/shopee-review/session'
    | '/api/shopee/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ShopeeReviewRoute: typeof ShopeeReviewRoute
  ApiShopeeReviewDataRoute: typeof ApiShopeeReviewDataRoute
  ApiShopeeReviewHealthRoute: typeof ApiShopeeReviewHealthRoute
  ApiShopeeReviewLoginRoute: typeof ApiShopeeReviewLoginRoute
  ApiShopeeReviewLogoutRoute: typeof ApiShopeeReviewLogoutRoute
  ApiShopeeReviewSessionRoute: typeof ApiShopeeReviewSessionRoute
  ApiShopeeOauthCallbackRoute: typeof ApiShopeeOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopee-review': {
      id: '/shopee-review'
      path: '/shopee-review'
      fullPath: '/shopee-review'
      preLoaderRoute: typeof ShopeeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/data': {
      id: '/api/shopee-review/data'
      path: '/api/shopee-review/data'
      fullPath: '/api/shopee-review/data'
      preLoaderRoute: typeof ApiShopeeReviewDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/health': {
      id: '/api/shopee-review/health'
      path: '/api/shopee-review/health'
      fullPath: '/api/shopee-review/health'
      preLoaderRoute: typeof ApiShopeeReviewHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/login': {
      id: '/api/shopee-review/login'
      path: '/api/shopee-review/login'
      fullPath: '/api/shopee-review/login'
      preLoaderRoute: typeof ApiShopeeReviewLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/logout': {
      id: '/api/shopee-review/logout'
      path: '/api/shopee-review/logout'
      fullPath: '/api/shopee-review/logout'
      preLoaderRoute: typeof ApiShopeeReviewLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee-review/session': {
      id: '/api/shopee-review/session'
      path: '/api/shopee-review/session'
      fullPath: '/api/shopee-review/session'
      preLoaderRoute: typeof ApiShopeeReviewSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopee/oauth/callback': {
      id: '/api/shopee/oauth/callback'
      path: '/api/shopee/oauth/callback'
      fullPath: '/api/shopee/oauth/callback'
      preLoaderRoute: typeof ApiShopeeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ShopeeReviewRoute: ShopeeReviewRoute,
  ApiShopeeReviewDataRoute: ApiShopeeReviewDataRoute,
  ApiShopeeReviewHealthRoute: ApiShopeeReviewHealthRoute,
  ApiShopeeReviewLoginRoute: ApiShopeeReviewLoginRoute,
  ApiShopeeReviewLogoutRoute: ApiShopeeReviewLogoutRoute,
  ApiShopeeReviewSessionRoute: ApiShopeeReviewSessionRoute,
  ApiShopeeOauthCallbackRoute: ApiShopeeOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
