// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-contacts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contacts_default = defineTool({
  name: "list_contacts",
  title: "Listar contatos",
  description: "Lista contatos do CRM. Suporta busca por nome/email/telefone e filtro por est\xE1gio do funil.",
  inputSchema: {
    search: z.string().optional().describe("Texto para buscar em nome, email, telefone ou WhatsApp."),
    funnel_status: z.string().optional().describe("Filtra por est\xE1gio do funil (ex.: novo_lead, qualificado, cliente_ativo, vip)."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, funnel_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb(ctx).from("contacts").select("id,name,email,phone,whatsapp,funnel_status,client_classification,lifetime_value,city,state,ultimo_contato").eq("is_active", true).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (funnel_status) q = q.eq("funnel_status", funnel_status);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`name.ilike.${s},email.ilike.${s},phone.ilike.${s},whatsapp.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { items: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_contact_default = defineTool2({
  name: "get_contact",
  title: "Detalhes do contato",
  description: "Retorna dados completos de um contato, seus pedidos recentes e hist\xF3rico recente.",
  inputSchema: { contact_id: z2.string().uuid().describe("ID do contato.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const c = sb2(ctx);
    const [{ data: contact, error: e1 }, { data: orders }, { data: history }] = await Promise.all([
      c.from("contacts").select("*").eq("id", contact_id).maybeSingle(),
      c.from("orders").select("id,order_number,status,total_value,order_date,due_date").eq("contact_id", contact_id).order("order_date", { ascending: false }).limit(10),
      c.from("contact_history").select("event_type,interaction_type,description,interaction_date").eq("contact_id", contact_id).order("interaction_date", { ascending: false }).limit(20)
    ]);
    if (e1) return { content: [{ type: "text", text: e1.message }], isError: true };
    if (!contact) return { content: [{ type: "text", text: "Contato n\xE3o encontrado" }], isError: true };
    const payload = { contact, orders: orders ?? [], history: history ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "Listar pedidos",
  description: "Lista pedidos com filtros opcionais por status, contato e intervalo de datas.",
  inputSchema: {
    status: z3.string().optional().describe("Ex.: pendente, em_producao, entregue, cancelado."),
    contact_id: z3.string().uuid().optional(),
    from_date: z3.string().optional().describe("Data m\xEDnima YYYY-MM-DD (order_date)."),
    to_date: z3.string().optional().describe("Data m\xE1xima YYYY-MM-DD (order_date)."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, contact_id, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb3(ctx).from("orders").select("id,order_number,status,total_value,order_date,due_date,contact_id").order("order_date", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (contact_id) q = q.eq("contact_id", contact_id);
    if (from_date) q = q.gte("order_date", from_date);
    if (to_date) q = q.lte("order_date", to_date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { items: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "Listar tarefas",
  description: "Lista tarefas com filtros por status, contato e datas (scheduled_date).",
  inputSchema: {
    status: z4.string().optional().describe("Ex.: pendente, em_andamento, concluida, on_hold."),
    contact_id: z4.string().uuid().optional(),
    from_date: z4.string().optional().describe("Data m\xEDnima YYYY-MM-DD."),
    to_date: z4.string().optional().describe("Data m\xE1xima YYYY-MM-DD."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, contact_id, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb4(ctx).from("tasks").select("id,title,status,scheduled_date,scheduled_time,due_date,contact_id,assigned_to,node_id").order("scheduled_date", { ascending: true }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (contact_id) q = q.eq("contact_id", contact_id);
    if (from_date) q = q.gte("scheduled_date", from_date);
    if (to_date) q = q.lte("scheduled_date", to_date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { items: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var ROOT_NODE = "d7c76db8-b7e0-4ce1-87ca-21275c346326";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool5({
  name: "create_task",
  title: "Criar tarefa",
  description: "Cria uma nova tarefa no Painel Central. Sempre vinculada ao n\xF3 raiz por padr\xE3o.",
  inputSchema: {
    title: z5.string().trim().min(1).describe("T\xEDtulo da tarefa."),
    scheduled_date: z5.string().optional().describe("Data agendada YYYY-MM-DD."),
    scheduled_time: z5.string().optional().describe("Hora HH:MM."),
    due_date: z5.string().optional().describe("Prazo YYYY-MM-DD."),
    contact_id: z5.string().uuid().optional().describe("Contato relacionado (opcional)."),
    node_id: z5.string().uuid().optional().describe("N\xF3 do organograma (padr\xE3o: raiz Deividi)."),
    assigned_to: z5.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const row = {
      title: input.title,
      status: "pendente",
      node_id: input.node_id ?? ROOT_NODE,
      contact_id: input.contact_id ?? null,
      scheduled_date: input.scheduled_date ?? null,
      scheduled_time: input.scheduled_time ?? null,
      due_date: input.due_date ?? null,
      assigned_to: input.assigned_to ?? null
    };
    const { data, error } = await sb5(ctx).from("tasks").insert(row).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Tarefa criada: ${data?.id}` }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financial_summary_default = defineTool6({
  name: "financial_summary",
  title: "Resumo financeiro",
  description: "Retorna totais a receber e a pagar (abertos e pagos) em um intervalo de datas de vencimento.",
  inputSchema: {
    from_date: z6.string().describe("Data inicial YYYY-MM-DD (due_date)."),
    to_date: z6.string().describe("Data final YYYY-MM-DD (due_date).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb6(ctx).from("financial_entries").select("type,status,value,value_paid,due_date").gte("due_date", from_date).lte("due_date", to_date);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const totals = { receber_total: 0, receber_pago: 0, pagar_total: 0, pagar_pago: 0, count: data?.length ?? 0 };
    for (const r of data ?? []) {
      const v = Number(r.value ?? 0), vp = Number(r.value_paid ?? 0);
      if (r.type === "receber") {
        totals.receber_total += v;
        totals.receber_pago += vp;
      } else if (r.type === "pagar") {
        totals.pagar_total += v;
        totals.pagar_pago += vp;
      }
    }
    return { content: [{ type: "text", text: JSON.stringify(totals) }], structuredContent: totals };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xkskyutmtlhivvpfxkjg";
var mcp_default = defineMcp({
  name: "painel-central-mcp",
  title: "Painel Central \u2013 C\xE9rebro",
  version: "0.1.0",
  instructions: "Ferramentas do Painel Central (CRM, pedidos, tarefas e financeiro). Use list_contacts/get_contact para consultar clientes, list_orders para pedidos, list_tasks e create_task para agenda, e financial_summary para totais a receber/pagar em um per\xEDodo.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_contacts_default,
    get_contact_default,
    list_orders_default,
    list_tasks_default,
    create_task_default,
    financial_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
